-- MySQL Script generated by MySQL Workbench
-- Fri Jan 29 14:06:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gruppe7
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(45) NULL,
  `epost` VARCHAR(45) NULL,
  `passord` VARCHAR(45) NULL,
  `studierettning` VARCHAR(45) NULL,
  `kull` YEAR NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `foreleser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foreleser` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(45) NULL,
  `epost` VARCHAR(45) NULL,
  `bildeadresse` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(45) NULL,
  `epost` VARCHAR(45) NULL,
  `passord` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fag` (
  `navn` INT NOT NULL,
  `foreleser_id` INT UNSIGNED NOT NULL,
  `emnekode` VARCHAR(10) NOT NULL,
  `pinkode` INT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`navn`, `foreleser_id`),
  INDEX `fk_fag_foreleser_idx` (`foreleser_id` ASC),
  CONSTRAINT `fk_fag_foreleser`
    FOREIGN KEY (`foreleser_id`)
    REFERENCES `foreleser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tilbakemelding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tilbakemelding` (
  `id` INT NOT NULL,
  `fag_navn` INT NOT NULL,
  `aar` YEAR NULL,
  `tekst` BLOB NULL,
  `student_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `fag_navn`, `student_id`),
  INDEX `fk_tilbakemelding_fag1_idx` (`fag_navn` ASC),
  INDEX `fk_tilbakemelding_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_tilbakemelding_fag1`
    FOREIGN KEY (`fag_navn`)
    REFERENCES `fag` (`navn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tilbakemelding_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `svar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svar` (
  `id` INT NOT NULL,
  `tilbakemelding_id` INT NOT NULL,
  `tilbakemelding_fag_navn` INT NOT NULL,
  `tekst` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_svar_tilbakemelding1_idx` (`tilbakemelding_id` ASC, `tilbakemelding_fag_navn` ASC),
  CONSTRAINT `fk_svar_tilbakemelding1`
    FOREIGN KEY (`tilbakemelding_id` , `tilbakemelding_fag_navn`)
    REFERENCES `tilbakemelding` (`id` , `fag_navn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
