-- MySQL Script generated by MySQL Workbench
-- Fri Feb  5 17:18:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gruppe7
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student` (
  `navn` VARCHAR(45) NULL,
  `epost` VARCHAR(45) NOT NULL,
  `passord` VARCHAR(45) NULL,
  `studierettning` VARCHAR(45) NULL,
  `kull` YEAR NULL,
  PRIMARY KEY (`epost`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `foreleser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foreleser` (
  `navn` VARCHAR(45) NULL,
  `epost` VARCHAR(45) NOT NULL,
  `bildeadresse` VARCHAR(45) NULL,
  `passord` VARCHAR(45) NULL,
  PRIMARY KEY (`epost`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(45) NULL,
  `epost` VARCHAR(45) NULL,
  `passord` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fag` (
  `navn` VARCHAR(45) NOT NULL,
  `emnekode` VARCHAR(10) NOT NULL,
  `pinkode` INT(4) NOT NULL,
  `foreleser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`emnekode`),
  INDEX `fk_fag_foreleser1_idx` (`foreleser` ASC),
  CONSTRAINT `fk_fag_foreleser1`
    FOREIGN KEY (`foreleser`)
    REFERENCES `foreleser` (`epost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tilbakemelding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tilbakemelding` (
  `fag` VARCHAR(45) NOT NULL,
  `tekst` BLOB NULL,
  `student` VARCHAR(45) NOT NULL)
--  PRIMARY KEY (`fag`, `student`)
--  INDEX `fk_tilbakemelding_fag1_idx` (`fag` ASC),
--  INDEX `fk_tilbakemelding_student1_idx` (`student` ASC),
--  CONSTRAINT `fk_tilbakemelding_fag1`
--    FOREIGN KEY (`fag`)
--    REFERENCES `fag` (`navn`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT `fk_tilbakemelding_student1`
--    FOREIGN KEY (`student`)
--    REFERENCES `student` (`epost`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
-- ENGINE = InnoDB;
;
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `svar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svar` (
  `fag` VARCHAR(45) NOT NULL,
  `student` VARCHAR(45) NOT NULL,
  `tekst` BLOB NULL,
  PRIMARY KEY (`fag`, `student`),
  CONSTRAINT `fk_svar_tilbakemelding1`
    FOREIGN KEY (`fag` , `student`)
    REFERENCES `tilbakemelding` (`fag` , `student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
